[package]
name = "mpl-auction-house"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []
test-bpf = []

[dependencies]
anchor-lang = "=0.19.0"
anchor-spl = "=0.19.0"
spl-token = { version = "=3.2",  features = ["no-entrypoint"] }
spl-associated-token-account = {version = "1.0.3", features = ["no-entrypoint"]}
mpl-token-metadata = { version="1.1.0", features = [ "no-entrypoint" ] }
thiserror = "1.0"
arrayref = "0.3.6"

[dev-dependencies]
anchor-client = "0.20.1"
shellexpand = "2.1.0"
serde_json = "1.0"
solana-program-test = "=1.9.5"
solana-program = "=1.9.5"
solana-sdk = "=1.9.5"
mpl-testing-utils={path="../../core/rust/testing-utils", version="0.0.1"}
env_logger="0.9.0"
